### ISSUE TITLE
protect main branch

### ISSUE THREAD

**Issue by jacopo-exact** [inogs/MITgcm_BC_IC#14]
and **never** push to main without PR and thorough review

cc @spiani @gbolzon

**Comment by spiani** [comment]
Unfortunately, this won’t be feasible in the short term. I understand this approach is considered best practice, but many team members at OGS aren’t yet familiar with this workflow. Implementing it now could disrupt their ability to work effectively. Once the team becomes more comfortable with pull requests, branches, and related processes, we can revisit this discussion.

**Comment by jacopo-exact** [comment]
I had to redo work because it was overwritten. We cannot rely on a project where we cannot guarantee the stability and functionality of the main branch.
