### ISSUE TITLE
Fishy assignment, please double check

### ISSUE THREAD

**Issue by jacopo-exact** [inogs/MITgcm_BC_IC#2]
While developing [MER](https://github.com/inogs/mer) I stumbled upon these assignments that smell like a bug,

https://github.com/inogs/MITgcm_BC_IC/blob/d4af24f5aed1774e2ea2296e32533dc3d8fb85ad/maskgen_006_014.py#L50-L52

These leave `E1t = np.ones((time,jpk,jpj,jpi),np.double)` to its initialisation value and swaps E2t and E1t.
Please double check that this is the intended behaviour, especially in light of the subsequent assignments in the output dataset:

https://github.com/inogs/MITgcm_BC_IC/blob/d4af24f5aed1774e2ea2296e32533dc3d8fb85ad/maskgen_006_014.py#L68-L70

cc: @gbolzon @spiani @stefanoquerin @pogmat

**Comment by gbolzon** [comment]
Thank you @jacopo-exact , 
you're right, it's a bug.
Fortunately, it does not impact anything.
Anyway, [here](https://github.com/inogs/MITgcm_BC_IC/commit/c6c7cc8f469934be8916e333621b588119316546) is the fix.
