### ISSUE TITLE
mask generator unused variables

### ISSUE THREAD

**Issue by jacopo-exact** [inogs/MITgcm_BC_IC#3]
Is it intended that `Glamt` and `Gphit` are defined and never used, and that variables with the same names are populated with lat/lon in the output file?

https://github.com/inogs/MITgcm_BC_IC/blob/c6c7cc8f469934be8916e333621b588119316546/maskgen_006_014.py#L74-L75

cc @gbolzon

**Comment by gbolzon** [comment]
Don't mind about that, glamt and gphit variables can be used by other codes. They are usually in mask NetCDF filest, the meaning is lon, lat.
